# Generated by Django 4.2 on 2024-10-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbHistorialclinicotbExploracionclinica',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Historial Clinico - Exploracion Clinica',
                'verbose_name_plural': 'Historiales Clinicos - Exploraciones Clinicas',
                'db_table': 'Tb_HistorialClinicoTb_ExploracionClinica',
                'managed': False,
            },
        ),
    ]
