# Generated by Django 4.2 on 2024-10-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbExploracionclinica',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Tipo', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Exploración Clínica',
                'verbose_name_plural': 'Exploraciones Clínicas',
                'db_table': 'Tb_ExploracionClinica',
                'managed': False,
            },
        ),
    ]
