# Generated by Django 4.2 on 2024-10-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbCita',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('horaentrada', models.TimeField(db_column='HoraEntrada')),
                ('horasalida', models.TimeField(db_column='HoraSalida')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'Tb_Cita',
                'managed': False,
            },
        ),
    ]
