# Generated by Django 4.2 on 2024-10-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbTratamientoclinico',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nombretratamiento', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='NombreTratamiento', max_length=100)),
            ],
            options={
                'verbose_name': 'Tratamiento Clinico',
                'verbose_name_plural': 'Tratamientos Clinicos',
                'db_table': 'Tb_TratamientoClinico',
                'managed': False,
            },
        ),
    ]
